# Generated by Django 5.0.2 on 2024-02-09 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('wakatime_created_at', models.DateTimeField(verbose_name='wakatime_created_at')),
                ('wakatime_token', models.CharField(max_length=255, verbose_name='wakatime_token')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
            },
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wakatime_data.profile', verbose_name='profile')),
            ],
            options={
                'verbose_name': 'day',
                'verbose_name_plural': 'days',
                'unique_together': {('date', 'profile')},
            },
        ),
        migrations.CreateModel(
            name='WakatimeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('CATEGORIES', 'categories'), ('EDITORS', 'editors'), ('LANGUAGES', 'languages'), ('MACHINES', 'machines'), ('SYSTEMS', 'operating_systems'), ('PROJECTS', 'projects')], max_length=10, verbose_name='category')),
                ('decimal', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='decimal')),
                ('digital', models.DurationField(verbose_name='digital')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('total_seconds', models.FloatField(verbose_name='total_seconds')),
                ('percent', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='percent')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wakatime_data.day', verbose_name='day')),
            ],
            options={
                'verbose_name': 'wakatime data',
                'verbose_name_plural': 'wakatime data',
                'unique_together': {('category', 'name')},
            },
        ),
    ]
