# Generated by Django 5.0.2 on 2024-02-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wakatime_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wakatimedata',
            name='digital',
            field=models.CharField(max_length=10, verbose_name='digital'),
        ),
    ]
